### PR TITLE
Make getVerticesPerPoint method public and improve tests

### LINKED ISSUE #840: :man_farmer:  `rviz_rendering` test regressions for GLSL 4.5
New test regression on the linux ci jobs:
```
projectroot.point_cloud_test_target
projectroot.point_cloud_renderable_test_target
rviz_rendering.PointCloudTestFixture.setRenderMode_regenerates_renderables_with_different_size_when_geometry_support_changes
rviz_rendering.PointCloudTestFixture.addPoints_adds_vertices_with_correct_geometry_when_called
rviz_rendering.PointCloudRenderableTestFixture.renderable_contains_a_correctly_filled_buffer
```
Reference: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2223/
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1895/

The package failing is `rviz_rendering` and the failing tests are: 

https://github.com/ros2/rviz/blob/f5f7c6a548b573959363307e9ad3ffab34acd93d/rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp#L267
https://github.com/ros2/rviz/blob/f5f7c6a548b573959363307e9ad3ffab34acd93d/rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp#L298
https://github.com/ros2/rviz/blob/f5f7c6a548b573959363307e9ad3ffab34acd93d/rviz_rendering/test/rviz_rendering/objects/point_cloud_renderable_test.cpp#L91

The underlying problem is that the opengl version used is 4.5(GLSL 4.5)  instead of Opengl 3.1 (GLSL 1.4), so probably these failing tests will have to be adjusted or the opengl version has to be fixed. All the tests seem to be covering the cases of GLSL>=120 and GLSL>=150, for the case of GLSL>=4.5 the tests seem to expect a similar behavior from the older version. 

Tagging package maintainers to get feedback. @jacobperron @mjeronimo

### PR DESCRIPTION
**Pull request by Blast545**
Should close #840 

I didn't have to extend existing API because it seems there's already API available to get the number of vertices being used after the render mode is set.

Opening as draft until I check with CI.

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Comment by Blast545** [comment]
Reproducing CI error on linux:
[Build Status](https://ci.ros2.org/job/ci_linux/16331/)

Testing with this PR:
[Build Status](https://ci.ros2.org/job/ci_linux/16332/)

**Comment by Blast545** [comment]
Ugh, didn't check the method is private. I had to make it public with e9961f48bf80e91aa5cfa84e3ab0e75d94c688f0, I'll rename the PR after is ready to be merged.

Testing again with this PR:
[Build Status](https://ci.ros2.org/job/ci_linux/16337/)

**Comment by Blast545** [comment]
PTAL @jacobperron

File: rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp [hunk 1]
```diff
@@ -259,11 +258,7 @@ TEST_F(
   renderables = point_cloud->getRenderables();
   for (auto const & renderable : renderables) {
     size_t number_of_vertices_per_box {0};
-    if (glsl_version >= 150) {
-      number_of_vertices_per_box = 1;
-    } else if (glsl_version >= 120) {
-      number_of_vertices_per_box = 6 * 3 * 2;  // six sides with two triangles each
-    }
+    number_of_vertices_per_box = point_cloud->getVerticesPerPoint();
```
Comment (clalancette) [inline rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp]: Nit: you can combine this statement with the one above, and just do:

```
size_t number_of_vertices_per_box = point_cloud->getVerticesPerPoint();
```

Also, in the loop in line 251 to 254, I think you should also call `getVerticesPerPoint`, as that seems to be better than hard-coding 1.

File: rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp [hunk 2]
```diff
@@ -281,15 +276,10 @@ TEST_F(PointCloudTestFixture, addPoints_adds_new_renderable_whenever_it_is_calle
...
-  int glsl_version = testing_environment_->getGlslVersion();
   auto point_cloud = std::make_shared<rviz_rendering::PointCloud>();
   point_cloud->setRenderMode(rviz_rendering::PointCloud::RM_FLAT_SQUARES);
   size_t number_of_vertices_per_flat_square = {0};
-  if (glsl_version >= 150) {
-    number_of_vertices_per_flat_square = 1;
-  } else if (glsl_version >= 120) {
-    number_of_vertices_per_flat_square = 3 * 2;  // two triangles for one square
-  }
+  number_of_vertices_per_flat_square = point_cloud->getVerticesPerPoint();
```
Comment (clalancette) [inline rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp]: Same comment here about combining this statement with the one above.

**Review by clalancette — CHANGES_REQUESTED** [review]
Overall, this looks like an improvement.  I left two small things to fix; once those are done, I'm happy to approve.

File: rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp (hunk 1 above)
Comment (Blast545) [reply rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp]: Addressed with 37d7bf1eeb3adeb0f67f9095021a057fc731380a

File: rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp (hunk 2 above)
Comment (Blast545) [reply rviz_rendering/test/rviz_rendering/objects/point_cloud_test.cpp]: Addressed with 5b71a093f6beaf74f5151bdd2974995be6c8cc33

**Comment by Blast545** [comment]
Thanks for the review @clalancette !

Full CI after addressing comments:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16342/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10954/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16706/)

**Review by clalancette — APPROVED** [review]
Thanks for the changes, this look good to me.

**Review by jacobperron — APPROVED** [review]
Thanks for looking into this :bow:

**Review by audrow — APPROVED** [review]

**Comment by clalancette** [comment]
CI is green, so I'm going to go ahead and merge this.
