### PR TITLE
Linting/fix rviz rendering

### LINKED ISSUE #34: [general] fix linters
fix issues in respect to linters

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
resolves https://github.com/ros2/rviz/issues/34 and enables a green build (modulo the issue with the ASSIMP_INCLUDE_DIRS). 

The first commit solves the remaining issues in rviz_rendering.
The second commit solves all issues regarding comments, whitespace and include order.
The remaining commits solve or disable the linter for a few issues, especially in the temp folder.

### CODE REVIEW

File: rviz_common/src/rviz_common/temp/default_plugins/displays/grid_display.cpp [hunk 1]
```diff
@@ -54,7 +54,7 @@
 #include "../../../selection/selection_manager.hpp"
 
 using rviz_rendering::Grid;
-using namespace rviz_common::properties;
+using namespace rviz_common::properties;  // NOLINT revisit later on
```
Comment (wjwwood) [inline rviz_common/src/rviz_common/temp/default_plugins/displays/grid_display.cpp]: Just replace with explicit using statements, e.g. `using rviz_common::properties::x; using rviz_common::properties::y;` etc...

This can be done in a follow up pr, but it should be done.

File: rviz_common/src/rviz_common/temp/stl_loader.cpp [hunk 2]
```diff
@@ -80,13 +80,13 @@ bool STLLoader::load(const std::string & path)
 
   // find the file size
   fseek(input, 0, SEEK_END);
-  long fileSize = ftell(input);
+  long fileSize = ftell(input);  // NOLINT maybe use int64 instead
```
Comment (wjwwood) [inline rviz_common/src/rviz_common/temp/stl_loader.cpp]: No maybe, just say `ftell` returns long, or use `auto`.

**Review by wjwwood — APPROVED** [review]
I'm going to go ahead and merge this, but please have a look at the two places I commented on commits.

File: rviz_common/src/rviz_common/temp/stl_loader.cpp (hunk 2 above)
Comment (anhosi) [reply rviz_common/src/rviz_common/temp/stl_loader.cpp]: I will use a better description in the comment.
Using `auto` will not work due to the comparison a few lines down between `fileSize` and `num_bytes_read`.

File: rviz_common/src/rviz_common/temp/default_plugins/displays/grid_display.cpp (hunk 1 above)
Comment (anhosi) [reply rviz_common/src/rviz_common/temp/default_plugins/displays/grid_display.cpp]: Follow up PR is in preparation.
