### PR TITLE
Fix Translation Issue in XYOrbitViewController

### LINKED ISSUE #1617: XYOrbit view is broken for steep view angles
### Generated by Generative AI

No

### Operating System:

```Linux ros2 6.14.0-34-generic #34~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep 23 15:35:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux```

### ROS version or commit hash:

jazzy, up to date as of 31/10-25

### RMW implementation (if applicable):

rmw_zenoh_cpp

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

<details><summary>ros2 doctor --report</summary>

```console
ros2 doctor --report
   NETWORK CONFIGURATION
   <hidden>

   PACKAGE VERSIONS
   <only rviz packages included>
rviz_ogre_vendor                          : latest=14.1.16, local=14.1.16
rviz_common                               : latest=14.1.16, local=14.1.16
rviz_default_plugins                      : latest=14.1.16, local=14.1.16
rviz_rendering                            : latest=14.1.16, local=14.1.16
rviz2                                     : latest=14.1.16, local=14.1.16
rviz_visual_tools                         : latest=4.1.4, local=4.1.4
rviz_assimp_vendor                        : latest=14.1.16, local=14.1.16

   PLATFORM INFORMATION
system           : Linux
platform info    : Linux-6.14.0-34-generic-x86_64-with-glibc2.39
release          : 6.14.0-34-generic
processor        : x86_64

   QOS COMPATIBILITY LIST
compatibility status    : No publisher/subscriber pairs found

   RMW MIDDLEWARE
middleware name    : rmw_zenoh_cpp

   ROS 2 INFORMATION
distribution name      : jazzy
distribution type      : ros2
distribution status    : active
release platforms      : {'debian': ['bookworm'], 'rhel': ['9'], 'ubuntu': ['noble']}

   TOPIC LIST
topic               : none
publisher count     : 0
subscriber count    :
```
</details>

### Steps to reproduce issue

1. Open rviz
2. Select XYOrbit in view selection
3. Rotate the view in a steep angle using single mouse drag
4. Translate the view using middle mouse dragging or shift + drag (here the issue occurs)

### Expected behavior

That the view would translate in the direction i am dragging the mouse proportional to my mouse movement like it did in ROS 1.
That when I change the view angle it would keep doing it proportionally no matter how steep the angle it is.

### Actual behavior

1. Directly from above it works as expected.
2. At smaller angles the view moves very jagged, and not proportional to the movement at all.
3. At large angles it is not possible to translate the view at all.

https://github.com/user-attachments/assets/f740aebc-1286-4090-a2fc-04ec666a4af6

### Additional information

It worked fine in ROS 1

### PR DESCRIPTION
**Pull request by eeshakumar**
## Description

Fixes #1617 

### Is this user-facing behavior change?

Yes, XY Orbit translation at steep camera angles is fixed

### Did you use Generative AI?

Test was generated using Cursor (Sonnet 4.5)

### Additional Information

https://github.com/user-attachments/assets/ca6e28ee-bafc-4bdf-8e87-2ce5ff4a3480

### CODE REVIEW

**Comment by eeshakumar** [comment]
@mjcarroll could you take a look?

File: rviz_default_plugins/include/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.hpp [hunk 1]
```diff
@@ -77,6 +77,9 @@ class RVIZ_DEFAULT_PLUGINS_PUBLIC XYOrbitViewController : public OrbitViewContro
    */
   void mimic(ViewController * source_view) override;
 
+  //Override to handle motion in XY plane, with proper mouse position access
```
Comment (ahcorde) [inline rviz_default_plugins/include/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.hpp]:
```suggestion
  // Override to handle motion in XY plane, with proper mouse position access
```

File: rviz_default_plugins/src/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.cpp [hunk 2]
```diff
@@ -200,6 +200,25 @@ void XYOrbitViewController::handleWheelEvent(
...
+void XYOrbitViewController::handleMouseEvent(rviz_common::ViewportMouseEvent & event)
+{
+  // Handle XY movement with proper mouse position access
+  if (event.middle() || (event.shift() && event.left())) {
+    int32_t diff_x = 0;
+    int32_t diff_y = 0;
+    bool moved = OrbitViewController::setMouseMovementFromEvent(event, diff_x, diff_y);
+    if (moved && (event.type == QEvent::MouseMove)) {
+      float distance = distance_property_->getFloat();
+      //Pass the last mouse position to maintain consistent motion
```
Comment (ahcorde) [inline rviz_default_plugins/src/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.cpp]:
```suggestion
      // Pass the last mouse position to maintain consistent motion
```

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to fix the linters https://build.ros2.org/job/Jpr__rviz__ubuntu_noble_amd64/102/ ?

File: rviz_default_plugins/include/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.hpp (hunk 1 above)
Comment (eeshakumar) [reply rviz_default_plugins/include/rviz_default_plugins/view_controllers/xy_orbit/xy_orbit_view_controller.hpp]: I've fixed these and other white space issues. Resolving

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Pulls: ros2/rviz#1630
Gist: https://gist.githubusercontent.com/ahcorde/b6c3533e13db5bb2951f199186247502/raw/9ccb1fca07f9469620aab6b4c328cc3cdb11596b/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_default_plugins
TEST args:  --packages-above rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17601
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26300/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19949/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/5997/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26043/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to retarget this PR to `rolling` ? then I can backport this to older distros.

**Comment by eeshakumar** [comment]
@ahcorde  thanks! I pulled the changes to a branch tracking rolling instead.

**Comment by ahcorde** [comment]
Pulls: ros2/rviz#1630
Gist: https://gist.githubusercontent.com/ahcorde/6476826cd23cfd0f0bb8b23a005a6df6/raw/9ccb1fca07f9469620aab6b4c328cc3cdb11596b/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_default_plugins
TEST args:  --packages-above rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17610
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26312/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19959/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6009/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26052/)

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport kilted jazzy humble
