### PR TITLE
Fix the order of destructors

### LINKED ISSUE #557: [laser scan] segmentation on invalid topic
The laser scan plugin makes RViz crash [segmentation fault -11] when selecting a wrong topic.

Steps to reproduce on OSX:

* ros2 launch dummy_robot_bringup dummy_robot_bringup_launch.xml
* Start Rviz2, add laser scan plugin, select "goal_pose" as topic.

### PR DESCRIPTION
**Pull request by spiralray**
In current code, nullptr is called on destructor of `MessageFilterDisplay`.
This causes segfault on OS X (with Clang++) (e.g. #557 #568 )

I only tested on OS X, so I don't know this fix is acceptable on Ubuntu and g++.
Can anyone test on Ubuntu?

### CODE REVIEW

**Comment by Karsten1987** [comment]
Thanks a lot for this PR. I can definitely verify that this solves #557. I am not aware of having seen that particular problem on Ubuntu.

File: rviz_common/include/rviz_common/message_filter_display.hpp [hunk 1]
```diff
@@ -151,8 +152,12 @@ class MessageFilterDisplay : public _RosTopicDisplay
...
   virtual void unsubscribe()
   {
-    subscription_.reset();
-    tf_filter_.reset();
+    if (tf_filter_) {
+      tf_filter_.reset();
+    }
+    if (subscription_) {
+      subscription_.reset();
+    }
```
Comment (Karsten1987) [inline rviz_common/include/rviz_common/message_filter_display.hpp]: I am having a problem with this, as I think it actually shims over the issue here. Calling `reset` on a shared pointer should always work, whether it's pointing to something or is indeed a `nullptr`.

I've just played around with this and I think the real cause is the order in which these two entities are getting destroyed. 
Looking at the initialization, there's `tf_filter_->connectInput(*subscription_);` which couples the `tf_filter` with the `subscription`. I've changed the order here - saying that you call `subscription_.reset()` first and then `tf_filter.reset()` and the issue is gone. So I think that would be the appropriate fix for this here.
But then again, I feel the real problem is actually within the destructor of either entity, the `tf_filter` as well as the message filter to verify that its dependencies don't dangle.

**Review by Karsten1987 — CHANGES_REQUESTED** [review]
I don't think that `if` is needed here. I think swapping the order in which the `subscription` as well as the `tf_filter` is getting destroyed is the right fix here.

File: rviz_common/include/rviz_common/message_filter_display.hpp (hunk 1 above)
Comment (spiralray) [reply rviz_common/include/rviz_common/message_filter_display.hpp]: First of all, argument `nullptr` is innocent as you pointed :)

However, `tf_filter_->connectInput` is not called on constructor, so `subscription_` has nullptr when this class is initialized.
```cpp
  MessageFilterDisplay()
  : subscription_(nullptr),
    tf_filter_(nullptr),
    messages_received_(0)
  {
    // TODO(Martin-Idel-SI): We need a way to extract the MessageType from the template to set a
    // correct string. Previously was:
    // QString message_type =
    //   QString::fromStdString(message_filters::message_traits::datatype<MessageType>());
    QString message_type = QString::fromStdString("");
    topic_property_->setMessageType(message_type);
    topic_property_->setDescription(message_type + " topic to subscribe to.");
  }
```

`subscription_` gets valid pointer for the first time when `MessageFilterDisplay::subscribe` is called.
So, I think we should check whether `subscription_` is null or not, on the destructor.

Comment (spiralray) [reply rviz_common/include/rviz_common/message_filter_display.hpp:160]: Sry, I misunderstood and I found that this also works well.
```cpp
  virtual void unsubscribe()
  {
    if (tf_filter_) {
      tf_filter_.message_connection_.disconnect();
    }
    
    subscription_.reset();

    if (tf_filter_) {
      tf_filter_.reset();
    }
  }
```

`tf_filter_.message_connection_` depends on subscription_ via callback function, and this is the underlying cause.
So, we should call `tf_filter_.message_connection_.disconnect` first if `tf_filter_` has valid pointer

Comment (spiralray) [reply rviz_common/include/rviz_common/message_filter_display.hpp]: If you want to reset `subscription_` first, I recommend following code.

```cpp
  virtual void unsubscribe()
  {
    if (tf_filter_) {
      tf_filter_.message_connection_.disconnect();
    }

    if(subscription_) {
      subscription_.reset();
    }

    if (tf_filter_) {
      tf_filter_.reset();
    }
  }
```

`tf_filter_.message_connection_` depends on subscription_ via callback function, and this is the underlying cause.
So, we should call `tf_filter_.message_connection_.disconnect` first if `tf_filter_` has valid pointer

Comment (Karsten1987) [reply rviz_common/include/rviz_common/message_filter_display.hpp]: Please apologize. I did not realize that your PR already changes the order. What I said earlier is actually wrong and your code is what I had in mind as well. Reset the tf filter, then the subscription. I still do believe we don't need the `if (tf_filter)` and `if(subscription)` clauses.
The following code works for me (additional to the changes you have in the constructor):
```
  virtual void unsubscribe()
  {
    tf_filter_.reset();
    subscription_.reset();
  }
```

Comment (spiralray) [reply rviz_common/include/rviz_common/message_filter_display.hpp]: Thanks for replying.
After I cleaned my workspace and rebuild, I verified that your opinion is right.
I'm sorry too.

I fixed the code :)

**Review by Karsten1987 — APPROVED** [review]
Thanks @spiralray for iterating with me over this.

**Review by wjwwood — APPROVED** [review]
lgtm

Fix makes sense, several accounts of fixing the issue from users. 👍

**Comment by Karsten1987** [comment]
CI to make sure (build all, test --packages-above-and-dependencies rviz_common)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11491/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6687/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9421/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11380/)
