### PR TITLE
Use dedicated TransformListener thread

### LINKED ISSUE #359: High latency in TF propagation
I'm porting the Stereolabs ZED 3D camera package to ROS2 and I cannot work with TF because of the high latency.
I'm sure that the TF messages propagates because I can see them using the `ros2 topic` and the `ros2 run tf2_ros tf2_echo` CLI commands... but Rviz receives them with many seconds of latency (sometimes I see frame axis move in Rviz after 2 or 3 three seconds after I stopped the node).

I thought that it was a problem with our node until I made a test with the "dummy robot" example and I figured out that the latency is a general problem:

 * Run the example:
   `$ ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py`
* Open `$ rviz2`
* Set the fixed frame to `world`
* Add a TF plugin viewer. You will see the robot link moving
* Add a `LaserScan` plugin and subscribe to `/scan`

At this point you will see the simulated laser scan on the oscillating link of the robot and you will notice how it is rendered in late respect to its reference frame.
Furthermore you will notice a lot of errors 
`Could not transform from [single_rrbot_hokuyo_link] to [world]` in the `LaserScan` plugin
and 
`[ERROR] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1538495387.01342 but the latest data is at time 1538495386.98954, when looking up transform from frame [single_rrbot_hokuyo_link] to frame [world]`
in the console where RVIZ2 has been executed

image

I read that a solution was provided for a similar issue and I updated ROS2 and Rviz2 to the latest version of the `master` branch, but the issue is still present.
I also tried to change RMW, but each of the three available options have the same problem.

### PR DESCRIPTION
**Pull request by ymd-stella**
Fixes #359.
Problem detail is https://github.com/ros2/rviz/issues/359#issuecomment-635695668.

### CODE REVIEW

**Comment by mikeferguson** [comment]
+1. This seems to make everything a lot smoother in RVIZ2 (for instance, when a robot arm is moving, it's very jerky without this patch).

File: rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp [hunk 1]
```diff
@@ -123,8 +123,13 @@ void TFWrapper::initialize(
   bool using_dedicated_thread)
 {
   initializeBuffer(clock, rviz_ros_node.lock()->get_raw_node(), using_dedicated_thread);
-  tf_listener_ = std::make_shared<tf2_ros::TransformListener>(
-    *buffer_, rviz_ros_node.lock()->get_raw_node(), false);
+  if (using_dedicated_thread) {
+    tf_listener_ = std::make_shared<tf2_ros::TransformListener>(
+      *buffer_, true);
```
Comment (Martin-Idel) [inline rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: This will actually create a new node, did you try what happens if you just use `std::make_shared<tf2_ros::TransformListener>(
    *buffer_, rviz_ros_node.lock()->get_raw_node(), true);` - shouldn't this already spin the TransformListener in a dedicated thread?

Comment (ymd-stella) [reply rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: `Node has already been added to an executor.` was shown.
relevant code:
- https://github.com/ros2/rclcpp/blob/0fa68d54e7018fd67fd5c597e690dd85796f1e33/rclcpp/src/rclcpp/executor.cpp#L122
- https://github.com/ros2/rviz/blob/0dc0f5bb52f57b57b631974241319ea80dc67373/rviz_common/src/rviz_common/visualization_manager.cpp#L236
- https://github.com/ros2/geometry2/blob/0188f9bdac47c32cd0563b41d24d13d79ce9437e/tf2_ros/src/transform_listener.cpp#L78

Comment (Martin-Idel) [reply rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: Okay, I see... So the correct way to solve this should be to actually make RViz multi-threaded and spin the transformer callback in its own thread then (and more often than e.g. the update loop). 

I guess this is a much more subtle undertaking, so I would propose:
- Add a "todo" comment that this actually introduces a new node and should be done via threading,
- Merge the PR since this fixes a big issue where there are multiple reports
- Open an issue (or use this one: https://github.com/ros2/rviz/issues/548) to track the todo

Comment (ymd-stella) [reply rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: > Add a "todo" comment that this actually introduces a new node and should be done via threading,

If you provide the concrete comment, I'll add them to this PR. (I don't know the format of the TODO comments on this project.)

Comment (Martin-Idel) [reply rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: No real schema except for linters. The following should do (you can also add your name, but I find the naming inconsistent, it's just enforced by cpplint)
```
TODO(anyone): The TransformListener needs very quick spinning so it uses its own node here. Remove this in favor of a multithreaded spinner and ensure that the listener callback queue does not fill up.
```
You'll probably need to split it up into multiple lines.

@jacobperron The error analysis seems sound and the solution works on several machines. When this got ported we explicitly avoided making new nodes if possible, but making RViz multithreaded requires much more work, since this is an issue many people complained about, I think this is a good compromise - unless @ymd-stella wants to jump in and do this of course.
Maybe you could take a quick look?

Comment (jacobperron) [reply rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: I agree that a multithreaded executor sounds like the best way to go. I'm okay with merging this workaround in the meantime with a TODO as you suggest.

Comment (ymd-stella) [reply rviz_default_plugins/src/rviz_default_plugins/transformation/tf_wrapper.cpp:131]: I've added the comment. I've written `TODO(pull/551)` to make it easier for those who found it to look up the details.

**Comment by jacobperron** [comment]
The Rpr_* job is failing for an unrelated reason.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11188/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6467/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9141/) (unrelated warning)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11103/) (unrelated warnings, already fixed on `ros2` I believe)

**Review by jacobperron — APPROVED** [review]
LGTM

@ymd-stella Thanks for the investigation and the patch!
