### PR TITLE
Putting glsl 1.50 resources back in RenderSystem

### LINKED ISSUE #662: Low FPS in PointCloud2 visualization
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binary
- Version or commit hash:
  - Foxy
  - rviz2: 8.2.1-1focal.20210226.004041
- DDS implementation:
  - Fast-RTPS 
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce the issue

1. Clone my test repository
  a. `git clone git@github.com:k0suke-murakami/send_lots_of_points_node_ros2.git` 
2. Clone pcl_perception
  a. `git@github.com:ros-perception/perception_pcl.git`
  b. `git checkout foxy-devel`
3. Build 
4. Run
  a. `rviz2` @Terminal1
  b. `ros2 run send_lots_of_points_node_ros2 send_lots_of_points_node_ros2 1 200 1000` @Terminal2

#### Expected behavior
Tested in ROS1(melodic) with similar code (https://github.com/k0suke-murakami/send_lots_of_points_node_ros1)
`rosrun send_lots_of_points_node send_lots_of_points_node 1 200 1000`
FPS is not low for visualizing 200*1000 points in ROS1. It is around 21FPS.

https://user-images.githubusercontent.com/10920881/110898827-50686b00-8343-11eb-9b17-e864342b4173.mp4

#### Actual behavior

FPS is almost 0.

https://user-images.githubusercontent.com/10920881/110898799-3fb7f500-8343-11eb-864e-97af48bdae08.mp4

### PR DESCRIPTION
**Pull request by pijaro**
GLSL version 1.50 resources were left commented out in `RenderSystem` class which resulted in performance hit in pointcloud rendering. #46 mentions this but was left behind for a long time now (2017). 

I tested putting back 1.50 locally and it worked fine on ubuntu 20.04. Therefore I think it is safe to assume that this is no longer an issue.

Presented PR puts back glsl 1.50 resources and updates corresponding unit tests. This improves pointcloud rendering a lot (on my machine it is about 200% for 21mln pointcloud while rendering with primitives).

This may also fix #662

### CODE REVIEW

File: rviz_rendering/test/rviz_rendering/ogre_testing_environment.hpp [hunk 1]
```diff
@@ -44,6 +44,8 @@ class OgreTestingEnvironment
   void setUpOgreTestEnvironment(bool debug = false);
 
   void setUpRenderSystem();
+
+  int getGlslVersion();
```
Comment (adamdbrw) [inline rviz_rendering/test/rviz_rendering/ogre_testing_environment.hpp]: This looks like a const function

**Comment by pijaro** [comment]
@jacobperron can you take a look at this PR, please?

**Comment by adamdbrw** [comment]
@mjeronimo this one improves performance by a lot with point clouds and should be a quick one to review, could you take a look?

**Review by mjeronimo — APPROVED** [review]
I think this is OK as a first step. Going forward, I'd rather see these differences encapsulated into an object with methods such as get_size_of_single_vertex and get_num_vertices_per_box, for example.

**Comment by jacobperron** [comment]
@pijaro Does this resolve https://github.com/ros2/rviz/issues/670, or is that a separate issue?

**Comment by adamdbrw** [comment]
@jacobperron @pijaro AFAIK this is a separate issue

**Comment by pijaro** [comment]
@jacobperron @adamdbrw That's correct, #670 is a separate issue.

**Review by jacobperron — APPROVED** [review]
LGTM pending CI
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14492/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9252/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12158/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14592/)

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by pijaro** [comment]
I just committed a fix for windows.

@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
@pijaro Thanks! Sorry, I meant to follow-up on that.

Windows: [Build Status](https://ci.ros2.org/job/ci_windows/14697/)

**Comment by adamdbrw** [comment]
@jacobperron Would this be a good candidate for a Foxy backport?

**Comment by jacobperron** [comment]
@adamdbrw It looks like there is an issue with this patch (https://github.com/ros2/rviz/pull/681). I think it'd be better to let this soak on the `ros2` branch, and then backport to Galactic. After it's had some time to soak in Galactic, I'd be open to backporting to Foxy.
