### PR TITLE
Fix map after upgrade

### LINKED ISSUE #453: Map rendering fails
RViz is failing to display a map and is spitting out OpenGL errors "GL_INVALID_OPERATION" (see log below). I'm using ROS2 Eloquent master and the latest RViz built from source.

The map is size 567 x 329 and the map data is indeed the correct size for the dimensions.

Notice the map is black in the RViz display:
Screenshot from 2019-08-26 15-01-13

```
[rviz2-1] [INFO] [rviz]: [signalFailure] Drop message: frame 'lidar_link' at time 1566847715.955 for reason(0)
[rviz2-1] [INFO] [rviz2]: Trying to create a map of size 202 x 161 using 1 swatches
[rviz2-1] [ERROR] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-1] active samplers with a different type refer to the same texture image unit
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
[rviz2-1] active samplers with a different type refer to the same texture image unit
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
[rviz2-1] active samplers with a different type refer to the same texture image unit
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
[rviz2-1] active samplers with a different type refer to the same texture image unit
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
[rviz2-1] active samplers with a different type refer to the same texture image unit
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
[rviz2-1] active samplers with a different type refer to the same texture image unit
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
```

### PR DESCRIPTION
**Pull request by Martin-Idel**
Fix #453 

This fixes the visual test after the latest upgrade and should therefore fix map rendering in general. Now, I only see one instance of 
```
[rviz_common:error] Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : active samplers with a different type refer to the same texture image unit, at /home/martin/gitRepos/ros/rviz_ws/src/rviz_rendering/src/rviz_rendering/ogre_logging.cpp:69
```
in the log, but I also see this way before the upgrade was done, so it's a different issue altogether.

### CODE REVIEW

**Comment by bpwilcox** [comment]
Fixes issue on my machine

File: rviz_default_plugins/src/rviz_default_plugins/displays/map/swatch.cpp [hunk 1]
```diff
@@ -30,7 +30,6 @@
 
 #include "rviz_default_plugins/displays/map/swatch.hpp"
 
-#include <algorithm>
```
Comment (jacobperron) [inline rviz_default_plugins/src/rviz_default_plugins/displays/map/swatch.cpp]: I think this should stay included since `std::copy` is used below.

**Review by jacobperron — COMMENTED** [review]
Though the map is rendering for me now, I do get the following error printed to the screen when the first map message is received:

```
[ERROR] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
active samplers with a different type refer to the same texture image unit
```

I'm not sure what is causing it.

**Comment by Martin-Idel** [comment]
@jacobperron: Yes, I also see this message, but actually I also see it without the upgrade. The message seems to be present for other people as well before the upgrade (for instance, see https://github.com/ros2/rviz/issues/458 - whatever version was used there, it was definitely *before* the OGRE upgrade, because the log message reads "Creating 1 swatches_" which was changed in https://github.com/ros2/rviz/commit/d52e5c10fa9e3a4beff29931f7543eebba40c99b before the upgrade).

I tried to get rid of that message also, but I couldn't do it without going really deep and as it was present before the upgrade, it seems to be a different problem.

File: rviz_default_plugins/src/rviz_default_plugins/displays/map/swatch.cpp (hunk 1 above)
Comment (Martin-Idel) [reply rviz_default_plugins/src/rviz_default_plugins/displays/map/swatch.cpp]: True and fixed. Linters are green for me now.

**Review by jacobperron — APPROVED** [review]
> I tried to get rid of that message also, but I couldn't do it without going really deep and as it was present before the upgrade, it seems to be a different problem.

Okay, perhaps we should open an issue regarding the error message for visibility.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8095/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4096/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6596/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7971/)

**Comment by jacobperron** [comment]
Follow-up ticket: https://github.com/ros2/rviz/issues/463
