### PR TITLE
Fix Potential Null Pointer Dereference in VisualizerApp::getRenderWindow() to Prevent Crashes

### LINKED ISSUE #1358: Fix Potential Null Pointer Dereference in VisualizerApp::getRenderWindow() to Prevent Crashes
### Operating System:

Linux shangzh-VMware-Virtual-Platform 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### ROS version or commit hash:

ros2 jazzy

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rviz

### 'ros2 doctor --report' output

```Formatted

```

## Environment
OS Version: Ubuntu 24.04
Compiler name and version number: Ubuntu clang version 18.1.3
Source or binary build?
source build
build options: --mixin asan-gcc

## Description
In the function VisualizerApp::getRenderWindow(), the current implementation does not check whether frame_ is null before calling frame_->getRenderWindow(). If frame_ is null (nullptr), this will result in a null pointer dereference, leading to a segmentation fault (SEGV) and program crash.

## Steps to Reproduce
Run the unit test:
```cpp
#include <gmock/gmock.h>
#include <memory>
#include <string>
#include <utility>
#include "rviz_common/visualizer_app.hpp"
#include "rviz_common/ros_integration/ros_client_abstraction_iface.hpp"

class MockRosNodeStorage : public rviz_common::ros_integration::RosClientAbstractionIface
{
 public:
   MOCK_METHOD4(
     init,
     rviz_common::ros_integration::RosNodeAbstractionIface::WeakPtr(
       int argc, char ** argv, const std::string & name, bool anonymous_name));
   MOCK_METHOD0(ok, bool());
   MOCK_METHOD0(shutdown, void());
};

TEST(VisualizerApp, handlesEmptyFrameDuringExit) {
   std::unique_ptr<rviz_common::ros_integration::RosClientAbstractionIface> ros_client =
     std::make_unique<MockRosNodeStorage>();
   EXPECT_CALL(*dynamic_cast<MockRosNodeStorage *>(ros_client.get()), shutdown()).Times(1);
   rviz_common::VisualizerApp visualizer_app(std::move(ros_client));
   // Simulate that frame_ is nullptr during exit, ensuring no crash occurs
   visualizer_app.getRenderWindow();
}
```
 The error log is as follows:
```markdown
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from VisualizerApp
[ RUN      ] VisualizerApp.handlesEmptyFrameDuringExit
AddressSanitizer:DEADLYSIGNAL
=================================================================
==282897==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000040 (pc 0x7edb4546ad2b bp 0x7ffe73a01e90 sp 0x7ffe73a01e80 T0)
==282897==The signal is caused by a READ memory access.
==282897==Hint: address points to the zero page.
    #0 0x7edb4546ad2b in rviz_common::VisualizationFrame::getRenderWindow() (/home/shangzh/ros2_jazzy/install/rviz_common/lib/librviz_common.so+0x86ad2b) (BuildId: 39789ab887abf563a7a1d60c39fc9c650a624184)
    #1 0x7edb454ad94a in rviz_common::VisualizerApp::getRenderWindow() (/home/shangzh/ros2_jazzy/install/rviz_common/lib/librviz_common.so+0x8ad94a) (BuildId: 39789ab887abf563a7a1d60c39fc9c650a624184)
    #2 0x615601560590 in VisualizerApp_handlesEmptyFrameDuringExit_Test::TestBody() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0xc9590) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #3 0x61560161c291 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x185291) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #4 0x615601609875 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x172875) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #5 0x6156015b027f in testing::Test::Run() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x11927f) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #6 0x6156015b1a5b in testing::TestInfo::Run() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x11aa5b) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #7 0x6156015b2db4 in testing::TestSuite::Run() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x11bdb4) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #8 0x6156015d9adf in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x142adf) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #9 0x61560161f6ec in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x1886ec) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #10 0x61560160cb12 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x175b12) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #11 0x6156015d60e9 in testing::UnitTest::Run() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0x13f0e9) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #12 0x61560158058a in RUN_ALL_TESTS() (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0xe958a) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #13 0x6156015804d6 in main (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0xe94d6) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)
    #14 0x7edb3fc2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #15 0x7edb3fc2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #16 0x6156015601d4 in _start (/home/shangzh/ros2_jazzy/build/rviz_common/rviz_common_visualizer_app_test+0xc91d4) (BuildId: aced2ab8292b9341e51fb4a4c444c17c7e679730)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/shangzh/ros2_jazzy/install/rviz_common/lib/librviz_common.so+0x86ad2b) (BuildId: 39789ab887abf563a7a1d60c39fc9c650a624184) in rviz_common::VisualizationFrame::getRenderWindow()
==282897==ABORTING

```

### Expected behavior

If frame_ is null, VisualizerApp::getRenderWindow() should return nullptr instead of causing a crash.

### Actual behavior

Crash

## Proposed Fix
```cpp
rviz_rendering::RenderWindow * VisualizerApp::getRenderWindow()
{
  if (!frame_) {
    return nullptr;
  }
  return frame_->getRenderWindow();
}

```

### PR DESCRIPTION
**Pull request by ahcorde**
Closes https://github.com/ros2/rviz/issues/1358

### CODE REVIEW

File: rviz_common/test/visualizer_app_test.cpp [hunk 1]
```diff
@@ -57,3 +57,12 @@ TEST(VisualizerApp, shutdownsRosDuringExit) {
...
   }
 }
+
+TEST(VisualizerApp, handlesEmptyFrameDuringExit) {
+  std::unique_ptr<rviz_common::ros_integration::RosClientAbstractionIface> ros_client =
+    std::make_unique<MockRosNodeStorage>();
+  EXPECT_CALL(*dynamic_cast<MockRosNodeStorage *>(ros_client.get()), shutdown()).Times(1);
+  rviz_common::VisualizerApp visualizer_app(std::move(ros_client));
+  // Simulate that frame_ is nullptr during exit, ensuring no crash occurs
+  visualizer_app.getRenderWindow();
```
Comment (christophebedard) [inline rviz_common/test/visualizer_app_test.cpp]: should you also check that this returns `nullptr`?

Comment (ahcorde) [reply rviz_common/test/visualizer_app_test.cpp]: https://github.com/ros2/rviz/pull/1359/commits/132f758995c6166f490ab36c6dbdb8e602f03e8e

**Comment by ahcorde** [comment]
Pulls: ros2/rviz#1359
Gist: https://gist.githubusercontent.com/ahcorde/99188b75c7da5a2479d8bc25d9bdbcd6/raw/b3b3950692e8ddc461c44a187c31f10aa7fbea75/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common
TEST args:  --packages-above rviz_common
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15551
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22977/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17199/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2466/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23853/)

**Review by christophebedard — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy humble
