### PR TITLE
UniformStringStream::parseFloat Fails to Handle Invalid Float Formats Correctly

### LINKED ISSUE #1357: UniformStringStream::parseFloat Fails to Handle Invalid Float Formats Correctly
### Operating System:

Linux shangzh-VMware-Virtual-Platform 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### ROS version or commit hash:

ros2 jazzy

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rviz

### 'ros2 doctor --report' output

```Formatted

```

## Description
The UniformStringStream::parseFloat method does not correctly handle certain invalid float formats, such as "1.2.3" and "4,5,6". When the input contains multiple decimal points or commas, the function fails to set the failbit state properly, causing the program to incorrectly accept partially invalid inputs instead of returning an error.

## Steps to Reproduce
1.Run the following test for parseFloat:
```cpp
#include <gtest/gtest.h>
#include <locale>
#include "rviz_common/uniform_string_stream.hpp"
using namespace rviz_common;  // NOLINT
TEST(UniformStringStream, parse_floats_invalid_float_format) {
   UniformStringStream uss("1.2.3 4,5");
   float a, b;
   uss.parseFloat(a);
   uss.parseFloat(b);
   EXPECT_FALSE(!!uss);
}
int main(int argc, char **argv) {
   testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
}
```

2.The test produces the following failure:
```markdown
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from UniformStringStream
[ RUN      ] UniformStringStream.parse_floats_invalid_float_format
/home/shangzh/ros2_jazzy/src/ros2/rviz/rviz_common/test/uniform_string_stream_test.cpp:10: Failure
Value of: !!uss
  Actual: true
Expected: false

[  FAILED  ] UniformStringStream.parse_floats_invalid_float_format (0 ms)
[----------] 1 test from UniformStringStream (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] UniformStringStream.parse_floats_invalid_float_format

 1 FAILED TEST

```

### Expected behavior

If the input format is invalid (e.g., "1.2.3" or "4,5,6"), parseFloat should correctly set the failbit, making the input stream invalid.

After parsing failure, calling !!uss should return false, indicating an error in the input stream.

### Actual behavior

parseFloat incorrectly parses part of the input (e.g., "1.2.3" might be parsed as 1.2) and does not trigger failbit, causing the program to incorrectly assume that the input is valid.

## Root Cause
1.parseFloat extracts a substring from the stream and creates a new UniformStringStream float_reader(float_string); but does not check whether the entire string has been successfully parsed.

2.float_reader >> f; only reads the first valid part of float_string but fails to detect extra characters, allowing "1.2.3" to be incorrectly interpreted as 1.2 without an error.

## Suggested Fix
Modify parseFloat to ensure that the entire string is parsed correctly, preventing the acceptance of invalid inputs:
```cpp
void UniformStringStream::parseFloat(float & f)
{
  std::string float_string;
  *this >> float_string;
  
  size_t comma_index = float_string.find(',');
  if (comma_index != std::string::npos) {
    float_string[comma_index] = '.';
  }

  UniformStringStream float_reader(float_string);
  float_reader >> f;
  
  // **New check**: Ensure the entire string is correctly parsed
  if (float_reader.fail() || !float_reader.eof()) {
    this->setstate(std::ios::failbit);
  }
}

```

### PR DESCRIPTION
**Pull request by ahcorde**
Closes https://github.com/ros2/rviz/issues/1357

### CODE REVIEW

File: rviz_common/src/rviz_common/uniform_string_stream.cpp [hunk 1]
```diff
@@ -61,6 +61,11 @@ void UniformStringStream::parseFloat(float & f)
   if (float_reader.fail()) {
     this->setstate(std::ios::failbit);
   }
+
+  // Ensure the entire string is correctly parsed
+  if (float_reader.fail() || !float_reader.eof()) {
+    this->setstate(std::ios::failbit);
+  }
```
Comment (christophebedard) [inline rviz_common/src/rviz_common/uniform_string_stream.cpp]:
```suggestion
  // Ensure the entire string is correctly parsed
  if (float_reader.fail() || !float_reader.eof()) {
    this->setstate(std::ios::failbit);
  }
```

Comment (christophebedard) [reply rviz_common/src/rviz_common/uniform_string_stream.cpp]: I'm not entirely familiar with this code, but would this cause `std::ios::failbit` to be set after the first `parseFloat()` call, since the string is not fully consumed after that? Or does it only consider a single number from the string?

**Comment by ahcorde** [comment]
Pulls: ros2/rviz#1360
Gist: https://gist.githubusercontent.com/ahcorde/88901a3939f4847a06912995bd2feb49/raw/aa3891a1cd8ce71218b8d869d2effe46ea11b1c4/ros2.repos
BUILD args:  --packages-above-and-dependencies rviz_common
TEST args:  --packages-above rviz_common
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15552
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22978/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17200/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2467/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23854/)

**Review by christophebedard — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy humble
